# Użyj obrazu bitnami/apache
FROM bitnami/apache

# Przejdź do folderu /app w kontenerze
WORKDIR /app

# Skopiuj zawartość bieżącego folderu do kontenera
ADD . /app

# Make port 80 available to the world outside this container
EXPOSE 8080

